name: playwright-cucumber-java-web
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project dependencies classpath
        run: mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

      - name: Install Playwright Browsers
        run: java -cp "$(cat cp.txt)" com.microsoft.playwright.CLI install

      - name: Run Tests
        run: mvn test -Dtest=your.package.name.YourTestClass

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: target/playwright-report
          retention-days: 30