name: playwright-cucumber-java-web

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project dependencies classpath
        run: mvn dependency:build-classpath -Dmdep.outputFile=cp.txt

      - name: Install Playwright Browsers
        run: |
          # Use the built classpath to run the CLI install command
          java -cp "$(cat cp.txt)" com.microsoft.playwright.CLI install

      - name: Run Tests
        run: mvn clean verify test
